### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by LevinJ** [balancap/SSD-Tensorflow#3]
Hi @balancap, Can you tell me which version of ternsorflow you are using with this project? Thanks.

I tried running train_ssd_network with tensorflow 0.11, and encountered below problem. 

AttributeError: module 'tensorflow.python.summary.summary' has no attribute 'image'

**Comment by balancap** [comment]
I just switched the last few days to TensorFlow 1.0. Unfortunately, Google made a few changes to the API for this release, so it is not entirely compatible with previous versions :/ From what I heard, the API should be more stable following the 1.0 release.

**Comment by LevinJ** [comment]
Ok, got it. Thanks.

**Comment by zbpjlc** [comment]
global_step always zero
